### PR TITLE
Added a fix for the nsfw not existing bug

### LINKED ISSUE #32: Getting animelist doesn't contain nsfw with official mal api
Hey
Just like [this person had pointed out](https://myanimelist.net/forum/?topicid=1909494), mal's api doesn't return all entries defaultly when requesting a user's animelist. For that, you need to include the nsfw=1 query parameter in the url.
Now, I'd say the default should be true, but I'd leave that decision to you. Anyway, the fix is a simple one - just add a parameter for the _animelist_ method which takes an "includeNsfw" boolean variable.

### PR DESCRIPTION
**Pull request by guydht**
Fixes #32

### CODE REVIEW

File: src/methods/malApi/user/index.ts [hunk 1]
```diff
@@ -41,13 +41,15 @@ export class MalUser {
     name: string = "@me",
     fields?: AnimeFields<T> | null,
     listStatusFields?: AnimeListStatusFields<S> | null,
+    includeNsfw?: boolean,
     args?: { status?: string; sort?: string; limit?: number; offset?: number }
```
Comment (PolyMeilex) [inline src/methods/malApi/user/index.ts:45]: I think that this should be treated like other args, and be part of args object.
For example if someone wants to set only `sort` arg, they should not be forced to supply unrelated `nsfw` flag, being part of args object allows this.

**Review by PolyMeilex — APPROVED** [review]

**Comment by PolyMeilex** [comment]
Thanks, and sorry for the delay.
